### ISSUE TITLE
Type[Injector] failure on 3.6

### ISSUE THREAD

**Issue by volcacius** [proofit404/dependencies#306]
Hello again,

I wanted to report a problem I'm experiencing on Python 3.6 using typing annotations:

```python
from typing import Type

from dependencies import Injector


class Wrapper:

    def __init__(self, injector: Type[Injector]):
        self.foo = injector.foo


Wrapper(Injector.let(foo='foo'))

```

gives me:

```python
Traceback (most recent call last):
  File "C:/brevitas/di_fail.py", line 6, in <module>
    class Wrapper:
  File "C:/brevitas/di_fail.py", line 8, in Wrapper
    def __init__(self, injector: Type[Injector]):
  File "C:\ProgramData\Miniconda3\envs\finn\lib\typing.py", line 679, in inner
    return cached(*args, **kwds)
  File "C:\ProgramData\Miniconda3\envs\finn\lib\typing.py", line 1143, in __getitem__
    orig_bases=self.__orig_bases__)
  File "C:\ProgramData\Miniconda3\envs\finn\lib\typing.py", line 1011, in __new__
    self.__tree_hash__ = (hash(self._subs_tree()) if origin else
  File "C:\ProgramData\Miniconda3\envs\finn\lib\typing.py", line 1086, in _subs_tree
    tree_args = _subs_tree(self, tvars, args)
  File "C:\ProgramData\Miniconda3\envs\finn\lib\typing.py", line 603, in _subs_tree
    tree_args.append(_replace_arg(arg, tvars, args))
  File "C:\ProgramData\Miniconda3\envs\finn\lib\typing.py", line 561, in _replace_arg
    if hasattr(arg, '_subs_tree') and isinstance(arg, (GenericMeta, _TypingBase)):
  File "C:\ProgramData\Miniconda3\envs\finn\lib\site-packages\_dependencies\injector.py", line 67, in __getattr__
    raise DependencyError(message)
_dependencies.exceptions.DependencyError: 'Injector' can not resolve attribute '_subs_tree'
```
The same issue is not raised on 3.7 and 3.8. 
Currently the obvious mitigation is to remove the type annotation.

Alessandro

**Comment by proofit404** [comment]
Hi, thank you for the report!

Indeed that's a conflict between typing module implementation and our `hasattr` behavior.

I think it worth fixing on our side. That's why I added the `bug` label.

Have a good day :palm_tree: 

Best regards,
Artem.
